import type { MachineType } from '../game/types'

function humanizeMachineType(machineType: MachineType): string {
  return machineType
    .split('_')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(' ')
}

function normalizeMachineName(machineName?: string): string | undefined {
  const normalizedMachineName = machineName?.trim()
  return normalizedMachineName && normalizedMachineName.length > 0
    ? normalizedMachineName
    : undefined
}

export function isAutoGeneratedMachineName(machineName: string, machineType?: MachineType): boolean {
  if (!machineType) {
    return false
  }

  const escapedTypeLabel = humanizeMachineType(machineType).replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  return new RegExp(`^${escapedTypeLabel} \\d+$`).test(machineName)
}

export function isRawMachineIdentifier(machineName: string): boolean {
  return /^machine_\d+$/i.test(machineName)
}

export function isMeaningfulMachineName(machineName: string | undefined, machineType?: MachineType): machineName is string {
  const normalizedMachineName = normalizeMachineName(machineName)
  return normalizedMachineName !== undefined
    && !isAutoGeneratedMachineName(normalizedMachineName, machineType)
    && !isRawMachineIdentifier(normalizedMachineName)
}

export function getPreferredCustomMachineName(
  primaryMachineName: string | undefined,
  fallbackMachineName: string | undefined,
  machineType?: MachineType,
): string | undefined {
  const normalizedPrimaryMachineName = normalizeMachineName(primaryMachineName)
  if (isMeaningfulMachineName(normalizedPrimaryMachineName, machineType)) {
    return normalizedPrimaryMachineName
  }

  const normalizedFallbackMachineName = normalizeMachineName(fallbackMachineName)
  if (isMeaningfulMachineName(normalizedFallbackMachineName, machineType)) {
    return normalizedFallbackMachineName
  }

  return undefined
}