import type { MachineType } from '../game/types'
import { getAllKnownMachineLabels } from '../i18n/i18n'

function normalizeMachineName(machineName?: string): string | undefined {
  const normalizedMachineName = machineName?.trim()
  return normalizedMachineName && normalizedMachineName.length > 0
    ? normalizedMachineName
    : undefined
}

function escapeRegex(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}

/**
 * Recognize an auto-generated default machine name for `machineType` in ANY
 * shipped locale, both the new no-space format (`Fabricator1`, `Vyráběč3`)
 * and the legacy space-separated humanized format (`Part Fabricator 1`).
 * Locale-agnostic — a save authored under EN still recognizes its auto
 * names after switching to CS so re-localization can rewrite them.
 */
export function isAutoGeneratedMachineName(machineName: string, machineType?: MachineType): boolean {
  if (!machineType) return false
  if (machineName.length === 0) return false
  for (const label of getAllKnownMachineLabels(machineType)) {
    const escaped = escapeRegex(label)
    if (new RegExp(`^${escaped}\\d+$`, 'u').test(machineName)) return true
    if (new RegExp(`^${escaped} \\d+$`, 'u').test(machineName)) return true
  }
  return false
}

export function isRawMachineIdentifier(machineName: string): boolean {
  return /^machine_\d+$/i.test(machineName)
}

export function isMeaningfulMachineName(machineName: string | undefined, machineType?: MachineType): machineName is string {
  const normalizedMachineName = normalizeMachineName(machineName)
  return normalizedMachineName !== undefined
    && !isAutoGeneratedMachineName(normalizedMachineName, machineType)
    && !isRawMachineIdentifier(normalizedMachineName)
}

export function getPreferredCustomMachineName(
  primaryMachineName: string | undefined,
  fallbackMachineName: string | undefined,
  machineType?: MachineType,
): string | undefined {
  const normalizedPrimaryMachineName = normalizeMachineName(primaryMachineName)
  if (isMeaningfulMachineName(normalizedPrimaryMachineName, machineType)) {
    return normalizedPrimaryMachineName
  }

  const normalizedFallbackMachineName = normalizeMachineName(fallbackMachineName)
  if (isMeaningfulMachineName(normalizedFallbackMachineName, machineType)) {
    return normalizedFallbackMachineName
  }

  return undefined
}