import { describe, it, expect } from 'vitest'
import { isAutoGeneratedMachineName, isMeaningfulMachineName } from '../../../src/ui/machineLabels'
import type { MachineType } from '../../../src/game/types'

/**
 * Tests for the expanded `isAutoGeneratedMachineName` (and its consumer
 * `isMeaningfulMachineName`) which must recognize ALL of:
 *   1. Legacy space-separated humanized: `Part Fabricator 3`, `Assembler 1`,
 *      `Factory Output 2`.
 *   2. New no-space humanized: `PartFabricator3`, `Assembler1`,
 *      `FactoryOutput2`.
 *   3. New no-space localized (EN labels from src/locales/en.json):
 *      `Fabricator3`, `Assembler1`, `Painter1`, `Recycler1`, `Splitter1`,
 *      `Shipper1`.
 *   4. New no-space localized (CS labels from src/locales/cs.json):
 *      `Vyráběč3`, `Montovač1`, `Lakovač1`, `Recyklovač1`, `Rozdělovač1`,
 *      `Odesílač2`.
 *
 * Custom names that MUST NOT match: `My Cool Bot`, `Bob`, `Fabricator-A`,
 * `Fabricator 1A`, empty string.
 *
 * Expected to FAIL until the recognition logic is expanded.
 */

interface Case {
  name: string
  type: MachineType
}

const LEGACY_HUMANIZED: Case[] = [
  { name: 'Part Fabricator 3', type: 'part_fabricator' },
  { name: 'Assembler 1', type: 'assembler' },
  { name: 'Factory Output 2', type: 'factory_output' },
  { name: 'Painter 5', type: 'painter' },
  { name: 'Recycler 9', type: 'recycler' },
  { name: 'Splitter 4', type: 'splitter' },
]

const NEW_NO_SPACE_HUMANIZED: Case[] = [
  { name: 'PartFabricator3', type: 'part_fabricator' },
  { name: 'Assembler1', type: 'assembler' },
  { name: 'FactoryOutput2', type: 'factory_output' },
  { name: 'Painter5', type: 'painter' },
  { name: 'Recycler9', type: 'recycler' },
  { name: 'Splitter4', type: 'splitter' },
]

const EN_LOCALIZED: Case[] = [
  { name: 'Fabricator3', type: 'part_fabricator' },
  { name: 'Assembler1', type: 'assembler' },
  { name: 'Painter1', type: 'painter' },
  { name: 'Recycler1', type: 'recycler' },
  { name: 'Splitter1', type: 'splitter' },
  { name: 'Shipper2', type: 'factory_output' },
]

const CS_LOCALIZED: Case[] = [
  { name: 'Vyráběč3', type: 'part_fabricator' },
  { name: 'Montovač1', type: 'assembler' },
  { name: 'Lakovač1', type: 'painter' },
  { name: 'Recyklovač1', type: 'recycler' },
  { name: 'Rozdělovač1', type: 'splitter' },
  { name: 'Odesílač2', type: 'factory_output' },
]

const CUSTOM_NAMES: Case[] = [
  { name: 'My Cool Bot', type: 'part_fabricator' },
  { name: 'Bob', type: 'assembler' },
  { name: 'Fabricator-A', type: 'part_fabricator' },
  { name: 'Fabricator 1A', type: 'part_fabricator' },
  { name: 'BobTheMachine', type: 'splitter' },
  { name: 'My Vyráběč', type: 'part_fabricator' },
]

describe('isAutoGeneratedMachineName — legacy space-separated humanized', () => {
  for (const c of LEGACY_HUMANIZED) {
    it(`recognizes "${c.name}" (type=${c.type}) as auto`, () => {
      expect(isAutoGeneratedMachineName(c.name, c.type)).toBe(true)
    })
  }
})

describe('isAutoGeneratedMachineName — new no-space humanized', () => {
  for (const c of NEW_NO_SPACE_HUMANIZED) {
    it(`recognizes "${c.name}" (type=${c.type}) as auto`, () => {
      expect(isAutoGeneratedMachineName(c.name, c.type)).toBe(true)
    })
  }
})

describe('isAutoGeneratedMachineName — EN localized (machines.* from en.json)', () => {
  for (const c of EN_LOCALIZED) {
    it(`recognizes "${c.name}" (type=${c.type}) as auto`, () => {
      expect(isAutoGeneratedMachineName(c.name, c.type)).toBe(true)
    })
  }
})

describe('isAutoGeneratedMachineName — CS localized (machines.* from cs.json)', () => {
  for (const c of CS_LOCALIZED) {
    it(`recognizes "${c.name}" (type=${c.type}) as auto`, () => {
      expect(isAutoGeneratedMachineName(c.name, c.type)).toBe(true)
    })
  }
})

describe('isAutoGeneratedMachineName — custom names', () => {
  for (const c of CUSTOM_NAMES) {
    it(`does NOT recognize "${c.name}" (type=${c.type}) as auto`, () => {
      expect(isAutoGeneratedMachineName(c.name, c.type)).toBe(false)
    })
  }

  it('does NOT recognize an empty string as auto', () => {
    expect(isAutoGeneratedMachineName('', 'assembler')).toBe(false)
  })

  it('does NOT recognize a label with no numeric suffix as auto', () => {
    expect(isAutoGeneratedMachineName('Fabricator', 'part_fabricator')).toBe(false)
    expect(isAutoGeneratedMachineName('Vyráběč', 'part_fabricator')).toBe(false)
  })
})

describe('isMeaningfulMachineName — follows isAutoGeneratedMachineName', () => {
  it('returns false for any auto-name format (legacy, no-space humanized, EN, CS)', () => {
    expect(isMeaningfulMachineName('Part Fabricator 1', 'part_fabricator')).toBe(false)
    expect(isMeaningfulMachineName('PartFabricator1', 'part_fabricator')).toBe(false)
    expect(isMeaningfulMachineName('Fabricator1', 'part_fabricator')).toBe(false)
    expect(isMeaningfulMachineName('Vyráběč1', 'part_fabricator')).toBe(false)
  })

  it('returns true for custom names', () => {
    expect(isMeaningfulMachineName('Bob', 'assembler')).toBe(true)
    expect(isMeaningfulMachineName('My Cool Bot', 'part_fabricator')).toBe(true)
    expect(isMeaningfulMachineName('Fabricator-A', 'part_fabricator')).toBe(true)
  })
})
