import { describe, it, expect, vi } from 'vitest'
import type { GameOverInfo, MachineType } from '../../../src/game/types'
import { wireGameOverModal } from '../../../src/ui/wireGameOverModal'

interface CapturedListener {
  (event: { data: unknown }): void
}

function makeGameOverInfo(overrides: Partial<GameOverInfo> = {}): GameOverInfo {
  return {
    reason: 'unconsumable_input',
    cause: 'machine_disabled',
    machineId: 'machine_6',
    itemId: 'item_1',
    itemType: 'wheel_small',
    tick: 42,
    ...overrides,
  }
}

describe('wireGameOverModal', () => {
  it('passes the machine display name through to the modal when the simulation provides it', () => {
    // GIVEN a simulation that can resolve both machine type and the exact
    // player-visible machine name for the stopped destination.
    let listener: CapturedListener | null = null
    const simulation = {
      on: vi.fn((_event: 'game_over', registeredListener: CapturedListener) => {
        listener = registeredListener
      }),
      getMachine: vi.fn((_machineId: string) => ({
        machineType: 'factory_output' as MachineType,
        name: 'North Dock Shipper',
      })),
    }
    const modal = {
      show: vi.fn(),
    }

    wireGameOverModal({
      simulation: simulation as never,
      modal: modal as never,
      resolveFallbackMachineType: vi.fn(() => undefined),
      resolveFallbackMachineName: vi.fn(() => undefined),
    })

    // WHEN the game-over event is forwarded to the modal.
    expect(listener).not.toBeNull()
    listener!({ data: makeGameOverInfo() })

    // THEN the forwarded modal payload should preserve the exact machine name,
    // not only the localized machine type.
    expect(modal.show).toHaveBeenCalledWith(expect.objectContaining({
      machineId: 'machine_6',
      machineType: 'factory_output',
      machineName: 'North Dock Shipper',
      itemType: 'wheel_small',
    }))
  })

  it('prefers the fallback custom name over an autogenerated simulation placeholder', () => {
    // GIVEN a simulation name that is only the autogenerated machine label,
    // while the fallback resolver still knows the player's custom machine name.
    let listener: CapturedListener | null = null
    const simulation = {
      on: vi.fn((_event: 'game_over', registeredListener: CapturedListener) => {
        listener = registeredListener
      }),
      getMachine: vi.fn((_machineId: string) => ({
        machineType: 'factory_output' as MachineType,
        name: 'Factory Output 2',
      })),
    }
    const modal = {
      show: vi.fn(),
    }
    const resolveFallbackMachineName = vi.fn(() => 'North Dock Shipper')

    wireGameOverModal({
      simulation: simulation as never,
      modal: modal as never,
      resolveFallbackMachineType: vi.fn(() => undefined),
      resolveFallbackMachineName,
    })

    // WHEN the game-over event is forwarded to the modal.
    expect(listener).not.toBeNull()
    listener!({ data: makeGameOverInfo() })

    // THEN the fallback custom name should win over the autogenerated
    // placeholder so the modal can show the player's actual label.
    expect(modal.show).toHaveBeenCalledWith(expect.objectContaining({
      machineId: 'machine_6',
      machineType: 'factory_output',
      machineName: 'North Dock Shipper',
      itemType: 'wheel_small',
    }))
  })
})